INSERT INTO STORE (NAME) VALUES ('Électronique');
INSERT INTO STORE (NAME) VALUES ('Vêtements');
INSERT INTO STORE (NAME) VALUES ('Alimentation');
INSERT INTO STORE (NAME) VALUES ('Sport');

INSERT INTO ITEMS (NAME, PRICE, STOCK) VALUES ('Laptop', 999.99, 10);
INSERT INTO ITEMS (NAME, PRICE, STOCK) VALUES ('Smartphone', 799.99, 20);
INSERT INTO ITEMS (NAME, PRICE, STOCK) VALUES ('Casque Audio', 149.99, 15);
INSERT INTO ITEMS (NAME, PRICE, STOCK) VALUES ('Clavier Mécanique', 89.99, 25);
INSERT INTO ITEMS (NAME, PRICE, STOCK) VALUES ('Souris Sans Fil', 39.99, 30);
INSERT INTO ITEMS (NAME, PRICE, STOCK) VALUES ('T-shirt', 19.99, 50);
INSERT INTO ITEMS (NAME, PRICE, STOCK) VALUES ('Jeans', 49.99, 40);
INSERT INTO ITEMS (NAME, PRICE, STOCK) VALUES ('Veste en Cuir', 129.99, 10);
INSERT INTO ITEMS (NAME, PRICE, STOCK) VALUES ('Sneakers', 79.99, 20);
INSERT INTO ITEMS (NAME, PRICE, STOCK) VALUES ('Casquette', 14.99, 35);
INSERT INTO ITEMS (NAME, PRICE, STOCK) VALUES ('Pomme', 0.99, 100);
INSERT INTO ITEMS (NAME, PRICE, STOCK) VALUES ('Bouteille dEau', 0.79, 200);
INSERT INTO ITEMS (NAME, PRICE, STOCK) VALUES ('Pain', 1.49, 80);
INSERT INTO ITEMS (NAME, PRICE, STOCK) VALUES ('Lait', 1.09, 60);
INSERT INTO ITEMS (NAME, PRICE, STOCK) VALUES ('Pâtes', 2.49, 90);
INSERT INTO ITEMS (NAME, PRICE, STOCK) VALUES ('Ballon de Football', 29.99, 20);
INSERT INTO ITEMS (NAME, PRICE, STOCK) VALUES ('Raquette de Tennis', 89.99, 15);
INSERT INTO ITEMS (NAME, PRICE, STOCK) VALUES ('Haltères (5 kg)', 49.99, 10);
INSERT INTO ITEMS (NAME, PRICE, STOCK) VALUES ('Tapis de Yoga', 24.99, 25);
INSERT INTO ITEMS (NAME, PRICE, STOCK) VALUES ('Vélo de Route', 499.99, 5);

INSERT INTO INVENTORY (ITEM_ID, STORE_ID) VALUES (1, 1);  -- Laptop
INSERT INTO INVENTORY (ITEM_ID, STORE_ID) VALUES (2, 1);  -- Smartphone
INSERT INTO INVENTORY (ITEM_ID, STORE_ID) VALUES (3, 1);  -- Casque Audio
INSERT INTO INVENTORY (ITEM_ID, STORE_ID) VALUES (4, 1);  -- Clavier Mécanique
INSERT INTO INVENTORY (ITEM_ID, STORE_ID) VALUES (5, 1);  -- Souris Sans Fil
INSERT INTO INVENTORY (ITEM_ID, STORE_ID) VALUES (6, 2);  -- T-shirt
INSERT INTO INVENTORY (ITEM_ID, STORE_ID) VALUES (7, 2);  -- Jeans
INSERT INTO INVENTORY (ITEM_ID, STORE_ID) VALUES (8, 2);  -- Veste en Cuir
INSERT INTO INVENTORY (ITEM_ID, STORE_ID) VALUES (9, 2);  -- Sneakers
INSERT INTO INVENTORY (ITEM_ID, STORE_ID) VALUES (10, 2); -- Casquette
INSERT INTO INVENTORY (ITEM_ID, STORE_ID) VALUES (6, 2);  -- T-shirt
INSERT INTO INVENTORY (ITEM_ID, STORE_ID) VALUES (7, 2);  -- Jeans
INSERT INTO INVENTORY (ITEM_ID, STORE_ID) VALUES (8, 2);  -- Veste en Cuir
INSERT INTO INVENTORY (ITEM_ID, STORE_ID) VALUES (9, 2);  -- Sneakers
INSERT INTO INVENTORY (ITEM_ID, STORE_ID) VALUES (10, 2); -- Casquette
INSERT INTO INVENTORY (ITEM_ID, STORE_ID) VALUES (16, 4); -- Ballon de Football
INSERT INTO INVENTORY (ITEM_ID, STORE_ID) VALUES (17, 4); -- Raquette de Tennis
INSERT INTO INVENTORY (ITEM_ID, STORE_ID) VALUES (18, 4); -- Haltères (5 kg)
INSERT INTO INVENTORY (ITEM_ID, STORE_ID) VALUES (19, 4); -- Tapis de Yoga
INSERT INTO INVENTORY (ITEM_ID, STORE_ID) VALUES (20, 4); -- Vélo de Route